language: cpp

sudo: required

dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Debug
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Debug
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Release

install:
  - '.ci/install.sh'

script:
  - '.ci/script.sh'

after_failure: 
  - cat Testing/Temporary/LastTest.log
  - cat Testing/Temporary/LastTestsFailed.log
